sudo: required

services:
  - docker

language: cpp

matrix:
  include:
   - os: linux
#     env: CC=gcc
#   - os: osx
#     env: CC=clang
#   - os: linux
#     env: CC=x86_64-w64-mingw32-gcc LDFLAGS="-static -s" CROSS=1
#     addons:
#       apt:
#         packages:
#           - gcc-mingw-w64-x86-64
#           - g++-mingw-w64-x86-64
#           - binutils-mingw-w64-x86-64
#           - mingw-w64-dev

install:
  # Install miniconda
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh; fi
  - bash Miniconda3-latest-*-x86_64.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH

  # Update and install conda packages
  - conda update --yes --all
  - conda install --yes anaconda-client conda-build

before_script:
  # Get version and number for the build
  - export BUILD_VERSION=$(git describe --tags --abbrev=0)
  - export BUILD_NUMBER=$(expr $(conda search --channel acellera plumed2 | grep " $BUILD_VERSION " | wc -l) + 1)
  - echo $BUILD_VERSION $BUILD_NUMBER

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash package/build_on_docker.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then conda build package; fi
  - ls -l linux-64

after_success:
 - export PATH=$HOME/miniconda/bin:$PATH
# - anaconda -t $ANACONDA_TOKEN upload  $HOME/miniconda/conda-bld/*-64/plumed2-*.tar.bz2 -u acellera
# - anaconda -t $ANACONDA_TOKEN upload  $HOME/miniconda/conda-bld/*-64/plumed2-[0-9]*.tar.bz2 -u acellera-basic 


