sudo: required

services:
  - docker

#branches:
# only:
#  - master

# More depth needed or git describe fails
# git:
#  depth: 1

language: cpp

#dist: precise

matrix:
  include:
   - os: linux
     env: CC=gcc
#   - os: osx
#     env: CC=clang
#   - os: linux
#     env: CC=x86_64-w64-mingw32-gcc LDFLAGS="-static -s" CROSS=1
#     addons:
#       apt:
#         packages:
#           - gcc-mingw-w64-x86-64
#           - g++-mingw-w64-x86-64
#           - binutils-mingw-w64-x86-64
#           - mingw-w64-dev

install:
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
 - if [ "$TRAVIS_OS_NAME" == "windows" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.sh -O miniconda.sh; fi

 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes 
 - conda update --all -y
 - conda install anaconda-client conda-build -y
 - conda config --add channels acellera

 - conda create -q -n travis-env 
 - source activate travis-env

 - git describe --tags
 - export BUILD_VERSION=$(git describe --tags | sed 's/-/ /g' | awk '{print $1}')
 - export BUILD_NUMBER=$(git describe --tags | sed 's/-/ /g' | awk '{print $2}')
 # Always set it to 0 so we don't get a new release at every successful commit
 - export BUILD_NUMBER=0

 - conda install -y tk
 - conda build  package/
 - conda install plumed2 --use-local

 - docker build --tag plumed2image docker

script:
  - echo


after_success:
 - export PATH="$HOME/miniconda/bin:$PATH"
 - echo $PATH
# - anaconda -t $ANACONDA_TOKEN upload  $HOME/miniconda/conda-bld/*-64/plumed2-*.tar.bz2 -u acellera
# - anaconda -t $ANACONDA_TOKEN upload  $HOME/miniconda/conda-bld/*-64/plumed2-[0-9]*.tar.bz2 -u acellera-basic 


