sudo: required

services:
  - docker

language: cpp

matrix:
  include:
   - os: linux
#     env: CC=gcc
#   - os: osx
#     env: CC=clang
#   - os: linux
#     env: CC=x86_64-w64-mingw32-gcc LDFLAGS="-static -s" CROSS=1
#     addons:
#       apt:
#         packages:
#           - gcc-mingw-w64-x86-64
#           - g++-mingw-w64-x86-64
#           - binutils-mingw-w64-x86-64
#           - mingw-w64-dev

install:
  # Install miniconda
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh; fi
  - bash Miniconda3-latest-*-x86_64.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH

  # Update and install conda packages
  - conda update --yes --all
  - conda install --yes anaconda-client conda-build

before_script:
  # Get version and number for the build
  - export BUILD_VERSION=$(git describe --tags --abbrev=0)
  - export BUILD_NUMBER=$(expr $(conda search --channel acellera plumed2 | grep " $BUILD_VERSION " | wc -l) + 1)
  - echo $BUILD_VERSION $BUILD_NUMBER

script:
  # Build and test
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash package/build_on_docker.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then conda build package; fi

after_success:
  # Check if a commit is from the master branch and tagged
  # Toni: Disabling the following check. Travis checks out in detached HEAD. 
  # Can't find a way to reliably extract the branch.
  # - if [ "$(git symbolic-ref --short HEAD)" != "master" ]; then exit 0; fi
  # Let's just assume we tag releases and branches we want to distribute.
  - if [ "$(git describe --tags --exact)" == "" ]; then exit 0; fi

  # Upload to anaconda.org
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then BUILD_PATH=$TRAVIS_BUILD_DIR/linux-64; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then BUILD_PATH=$HOME/miniconda/conda-bld/osx-64; fi
  - anaconda --token $ANACONDA_TOKEN upload --user acellera $BUILD_PATH/plumed2-*.tar.bz2
