package:
 name: plumed2
 version: {{ environ.get('BUILD_VERSION', "0.0.1" ) }}
 
about:
 home: http://www.plumed.org/
 license: LGPL
 summary: PLUMED is an open source library for free energy calculations in molecular systems

source:
  - git_url: https://github.com/plumed/plumed2
    git_rev: v2.3.2
  - path: $RECIPE_DIR/\.\./acemd2_plugin
    folder: acemd2_plugin

build:
 number: {{ environ.get('BUILD_NUMBER', 0 ) }}
 script_env:
  - FC
  - CC
  - CXX
  - TRAVIS_OS_NAME

test:
  source_files:
    # Files for PLUMED tests
    - regtest

    # Files for ACEMD2 plugin tests
    - acemd2_plugin/Makefile
    - acemd2_plugin/test.c

  commands:
    - export CPATH=$PREFIX/include
    - export LD_LIBRARY_PATH=$PREFIX/lib
    - printenv

    # Test ACEMD2 plugin
    - cd $SRC_DIR/acemd2_plugin && make check

    # Test PLUMED
    - cd $SRC_DIR/regtest && make | tee plumed.test.log
    - exit $(grep --count ERROR plumed.test.log)
