package:
 name: plumed2
 version: {{ environ.get('BUILD_VERSION', "2.3.0" ) }}

source:
 url: https://github.com/plumed/plumed2/archive/v2.3.0.tar.gz

build:
 number: {{ environ.get('BUILD_NUMBER', 0 ) }}
 script_env:
  - FC
  - CC
  - CXX
  - TRAVIS_OS_NAME


requirements:
 build:

 run:

about:
 license: "LGPL"
