package:
 name: plumed2
 version: {{ environ.get('BUILD_VERSION', "0.0.1" ) }}

build:
 number: {{ environ.get('BUILD_NUMBER', 0 ) }}
 script_env:
  - FC
  - CC
  - CXX


source:
 path: ../

requirements:
 build:

 run:

about:
 license: "LGPL"
