package:
 name: plumed2
 version: {{ environ.get('BUILD_VERSION', "0.0.1" ) }}

source:
 git_url: https://github.com/plumed/plumed2
 git_rev: v2.3.0

build:
 number: {{ environ.get('BUILD_NUMBER', 0 ) }}
 script_env:
  - FC
  - CC
  - CXX
  - TRAVIS_OS_NAME


requirements:
 build:
  - gcc

 run:

about:
 license: "LGPL"
