package:
 name: plumed2
 version: {{ environ.get('BUILD_VERSION', "0.0.1" ) }}
 
about:
 home: http://www.plumed.org/
 license: LGPL
 summary: PLUMED is an open source library for free energy calculations in molecular systems

source:
 git_url: https://github.com/plumed/plumed2
 git_rev: v2.3.2


requirements:
 build:
  - tk
 run:


build:
 number: {{ environ.get('BUILD_NUMBER', 0 ) }}
 script_env:
  - FC
  - CC
  - CXX
  - TRAVIS_OS_NAME


# test:
#  commands:
#  - cd $SRC_DIR/regtest && make -j2

